name: Unit and Integration Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Playwright Browsers
      run: |
        cd WorkoutManager.E2E.Tests
        pwsh bin/Release/net9.0/playwright.ps1 install chromium --with-deps
    
    - name: Run E2E Tests
      run: dotnet test WorkoutManager.E2E.Tests --no-build --configuration Release --logger "trx;LogFileName=e2e-tests.trx"
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/TestResults/*.trx'
    
    - name: Generate Coverage Report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"CoverageReport" -reporttypes:"Html;Cobertura"
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: CoverageReport/
    
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: '**/coverage.cobertura.xml'
        badge: true
        format: markdown
        output: both